== Protection Profile for Encrypting Retransmission Device

[cols="1,1,1,1,1,1,1,1"]
|===
8+|encrypting-retransmission-device 
| https://github.com/commoncriteria/encrypting-retransmission-device/tree/main[main] 
a| https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission-device-release.html[📄]
a|[link=https://github.com/commoncriteria/encrypting-retransmission-device/blob/gh-pages/main/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/encrypting-retransmission-device/gh-pages/main/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/encrypting-retransmission-device/blob/gh-pages/main/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/encrypting-retransmission-device/gh-pages/main/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/encrypting-retransmission-device/blob/gh-pages/main/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/encrypting-retransmission-device/gh-pages/main/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/encrypting-retransmission-device/blob/gh-pages/main/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/encrypting-retransmission-device/gh-pages/main/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/encrypting-retransmission-device/gh-pages/main/transforms.svg[transforms,150]
a|
https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission-device-esr.html[encrypting-retransmission-device-esr.html] +
https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission-device-release-linkable.html[encrypting-retransmission-release-linkable.html] +
https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission-device-release.html[encrypting-retransmission-release.html] +
https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission.html[encrypting-retransmission.html] +
|===

https://github.com/commoncriteria/encrypting-retransmission-device/issues[image:https://img.shields.io/github/issues/commoncriteria/encrypting-retransmission-device.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile for
Encrypting Retransmission Device based on the
https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission-device-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this Protection Profile
can be found link:Encrypting Retransmission Device[here].

=== Draft Version

* https://commoncriteria.github.io/encrypting-retransmission-device/main/encrypting-retransmission-device-release.html[Protection
Profile for Encrypting Retransmission Device] (html)
* https://commoncriteria.github.io/pp/QQQQ/QQQQ-release.pdf[Protection
Profile for Encrypting Retransmission Device] (pdf)

=== Release Version

* link:Encrypting Retransmission Device[Protection Profile for Encrypting Retransmission Device]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/encrypting-retransmission-device/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/encrypting-retransmission-device.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
